### PR TITLE
fix: added 'wrapper' suffix to the CustomInput wrapper's id

### PR DESCRIPTION
**Pull request by alemagio**
I added the PR without waiting for response LOL

### CODE REVIEW

**Comment by WilliamDASILVA** [comment]
Thank you for taking the time to make this PR.
Yet it won't solve the issue because there is still 2 elements having the same id in the page (the customInput & the pickerContainer).

**Comment by alemagio** [comment]
Hi, thanks for the reply
I updated the PR with the fix I think is the best: the id prop is not assigned as it is to any component but always has a suffix to describe to which element is attached to.
This is my opinion, if you prefer to use the id prop without modifications to the custom-input (for example) just let me know ;)

**Comment by WilliamDASILVA** [comment]
Hello @alemagio,
I'm closing this PR in favor of #211 because I'll use the picker attributes instead of having a custom `id` prop for every component.
In the minor refactor I've made, I somehow included your change if you wanna check out.

Again, thank you!

**Comment by alemagio** [comment]
Ok, thanks for the explanation and i will check your changes

**Pull request closed without merging**
