### PR TITLE
Changed version of moment from 2.24.0 to 2.29.1

### PR DESCRIPTION
**Pull request by uk-ohashi**
moment has been changed in Japanese month notation since version 2.25.
I would like to reflect this changed.

### CODE REVIEW

**Comment by ryanleit** [comment]
When this pull request is merge and public ?

**Comment by ryanleit** [comment]
@uk-ohashi when your fixing is approved ?

**Comment by uk-ohashi** [comment]
@WilliamDASILVA Hi, I've submitted PR. Can you review it?

**Comment by mtgto** [comment]
Perhaps #164 solves this problem.

**Pull request closed without merging**
