### PR TITLE
WIP feat: Add vue 3 support

### PR DESCRIPTION
**Pull request by crutch12**
solves #315 

What's new:
- updated dependencies
- updated vue v-modal usage (https://v3.vuejs.org/guide/migration/v-model.html)
- added emits option (https://v3.vuejs.org/guide/component-custom-events.html)
- renamed transition class names (https://v3.vuejs.org/guide/migration/transition.html)
- fixed transition-group usage (https://github.com/vuejs/docs-next/issues/648)
- mounting vue app using `createApp` function (https://v3.vuejs.org/api/global-api.html#createapp)
- removed `noValueToCustomElem` prop and added new slots support (https://v3.vuejs.org/guide/migration/slots-unification.html)
- renamed `beforeDestroy` -> `beforeUnmount`
- updated unit tests (dependencies, api calls)
- updated eslint rules (v-bind="object" is now order-sensitive - https://v3.vuejs.org/guide/migration/v-bind.html)
- v-click-outside doesn't support vue 3, so I've created a local copy until lib will be ready to use

TODO:
- nuxt doesn't support vue3 (https://github.com/nuxt/nuxt.js/issues/5708)
- vue-test-utils-next doesn't support `setData` yet (https://github.com/vuejs/vue-test-utils-next/issues/228) 
- rewrite mixin `keyboard-accessibility.js` using `composition-api` methods

### CODE REVIEW

**Comment by crutch12** [comment]
@WilliamDASILVA I think we should create @next branch (and npm tag) for this update

**Comment by victorybiz** [comment]
Any updates on Support of Vue 3?

**Comment by aGrahamAtFuji** [comment]
any more updates for support of Vue 3?

**Comment by issei-m** [comment]
Any update?

**Comment by cahyowhy** [comment]
already one year here :(

**Comment by crutch12** [comment]
@cahyowhy as I can see @WilliamDASILVA merged this branch and published 3.0.0-alpha.0 - https://www.npmjs.com/package/vue-ctk-date-time-picker/v/3.0.0-alpha.0

**Pull request merged**
