### PR TITLE
Add SSR & Nuxt Support

### PR DESCRIPTION
**Pull request by LouisMazel**

### CODE REVIEW

**Comment by qinglong-kooboo** [comment]
still not working with nuxt

**Comment by dmitry** [comment]
@LouisMazel why it was closed?

**Comment by goviedo** [comment]
This component is really amazing, please open this issue. The issue is still there.

npm run generate 

its fails with Reference Error: windows is not defined

**Comment by WilliamDASILVA** [comment]
Thanks for your interest in this feature.
I've re-opened the original issue related to this #75

**Comment by WilliamDASILVA** [comment]
Hello,
This has been fixed under the `v2.3.0` tag. Open a new issue if the problem persists.

**Pull request closed without merging**
